### ISSUE TITLE
Just to drop by and say thanks you!

### ISSUE THREAD

**Issue by kwccoin** [justin2004/slimv_box#2]
Of course if there is gui version it would be much better.  But as it is for someone struggle for months to setup this up, thanks you thanks you thanks you!!!!!

A few things:

a) you need to use insert on the REPL to do command, recall and execution.  It is part of VIM and have two modes

b) Part 3 is not really understandable as the debug etc. is not easy to be followed.

c) sometimes need to use (in-package :morse) in the real

d) you need to (ql:quickload :split-sequence) as even (use ... :split-sequence) does not auto load it

**Comment by kwccoin** [comment]
just thanks you note

**Comment by justin2004** [comment]
I'm glad slimv_box helped you!

If you want to improve the tutorial you can open a PR here:
https://github.com/kovisoft/slimv-tutorial
